### ISSUE TITLE
Todo for SCDS-PB

### ISSUE THREAD

**Issue by Enigmatisms** [Enigmatisms/scds-pb#1]
To make sure I have a rather deep understanding of k-d tree, BVH and space subdivision trees (quad/oct trees), there are few more things to be done:
- [ ] k-d tree as the ray-intersection accelerating structure for [AdaPT](https://github.com/Enigmatisms/AdaPT), which currently only supports the simplest BVH (suboptimal)
- [ ] BVH tree implementation in AdaPT should be migrated here (to review)
- [ ] CUDA implementation of k-d tree (to enhance CUDA coding capabilities). This can be very... weird, since I am currently not sure how GPU acceleration could help here.
- [ ] In this repo, I will implement my own thread-pool for ray-intersection CPU scheduling.
